# Generated by Django 6.0.5 on 2026-05-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sourceIp', models.GenericIPAddressField()),
                ('eventType', models.CharField(choices=[('BRUTE_FORCE', 'Brute Force Attack'), ('SQL_INJECTION', 'SQL Injection'), ('MALWARE_BEACON', 'Malware Beaconing'), ('PORT_SCAN', 'Port Scan')], max_length=20)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium')], max_length=10)),
                ('status', models.CharField(choices=[('BLOCKED', 'Blocked'), ('ISOLATED', 'Isolated'), ('MONITORING', 'Monitoring')], max_length=15)),
            ],
        ),
    ]
